#' Makes a summary table of estimated and placebo p values from output generated by BHC or IM placebos.
#'
#' @param plbo An object created by placebo_bch or placebo_im.
#' @param adjust Label the table with BCH or IM according to which one is chosen.
#'
#' @return Generates a tinytable object. This gives the regression and placebo p values and the proportion
#' of placebo simulation significant at 5\% as the number of clusters increases.
#'  The regression confidence interval and its width are also reported. The next part of the table gives
#'  the z-score of a Moran test, using 5 nearest neighbours, the R2 of a regression of the treatment on the
#'  principal components of the tensor, and the effective range and structure of this regression's residuals.
#' @export
#'
#' @examples
#' library(spatInfer)
#' data(opportunity)
#' # Choose a sample of 250 observations and run only nSim=100 placebo simulations to speed things up.
#' set.seed(123)
#' opportunity=opportunity |> dplyr::slice_sample(n=250)
#' # Use the number of splines and PCs indicated by optimal_basis()
#' plbo_bch=placebo_bch(mobility~racial_seg+single_mom,  opportunity,
#' splines=4, pc_num=3,nSim=100)
#'
#' placebo_table(plbo_bch,adjust="BCH")

placebo_table=function(plbo,adjust="BCH"){
##plbo is output of placebo function

rr=plbo$Results|>
  dplyr::mutate(dplyr::across(dplyr::where(is.numeric),~{round(.x,2)}))
ss=plbo$Spatial_Params|>
  dplyr::mutate(dplyr::across(dplyr::where(is.numeric),~{round(.x,2)}))

plac_tab=tinytable::tt(rr[,-c(1)],theme="striped",align="r",digits=2,
              notes=   list(
                paste0("Moran=",ss$Moran,
                       ", Structure=",ss$Structure,
                       ", Effective Range=",ss$Effective_Range,
                       ", R2=",ss$R2,"."
                       ),
                paste0("Splines=",ss$Splines,
                       ", PCs=",ss$PCs,"."
                ),
                "Estimated and placebo p values and proportion of placebo regressions significant at 5%, along
                with confidence intervals. R2 gives the explanatory power of a regression of the treatment on the principal components."
              )
)
  if(adjust=="BCH"){
    plac_tab= plac_tab |>
      tinytable::group_tt(i = list("HC" = 1, "BCH" = 2 ))
  }else{
    plac_tab= plac_tab |>
      tinytable::group_tt(i = list("HC" = 1, "IM" = 2 ))
  }

plac_tab= plac_tab |>
   tinytable::style_tt(
    i = c(1, 3),
    align = "l",
    bold=T)|>
  tinytable::style_tt(i = 0, bold=T ) |>
  tinytable::style_tt(j = c("Plac 5%"), color = "orange")

return(plac_tab)
}
