
#' Makes a summary table of estimated and synthetic outcome p values from output generated by BHC or IM simulations.
#'
#' @param syn An object containing simulation results created by synth_bch or synth_im.
#' @param adjust  What to label entries: BCH or IM
#'
#' @return Generates a tinytable object. This gives the regression and synthetic outcome p values as the number of clusters increases.
#'  The regression confidence interval and its width are also reported. The next part of the table gives
#'  the z-score of a Moran test, using 5 nearest neighbours, the R2 of a regression of the outcome on a
#'  quadratic in longitude and latitude, and the effective range and structure of this regression's residuals.
#' @export
#'
#' @examples
#' library(spatInfer)
#' data(opportunity)
#' # Choose a sample of 250 observations and run only 100 placebo simulations to speed things up.
#' set.seed(123)
#' opportunity=opportunity |> dplyr::slice_sample(n=250)
#' # Use the number of splines and PCs indicated by optimal_basis()
#' syn_bch=synth_bch(mobility~racial_seg+single_mom,  opportunity,
#' splines=4, pc_num=3,nSim=100)
#'
#' synth_table(syn_bch,adjust="BCH")


synth_table=function(syn,adjust="BCH"){

rr=syn$Results
rr=rr |>
  dplyr::select(-dplyr::contains("_05"))|>
  dplyr::mutate(dplyr::across(dplyr::where(is.numeric),~{round(.x,2)}))
ss=syn$Spatial_Params
ss=ss |>
  dplyr::mutate(dplyr::across(dplyr::where(is.numeric),~{round(.x,2)}))

syn_tab=tinytable::tt(rr[,-c(1)],theme="striped",align="r",digits=2 ,
              notes=   list(
                paste0("Moran=",ss$Moran,
                       ", Structure=",ss$Structure,
                       ", Effective Range=",ss$Effective_Range,
                       ", R2=",ss$R2,"."
                ),
                paste0("Splines=",ss$Splines,
                       ", PCs=",ss$PCs,"."
                ),
                "Estimated and synthetic outcome p values for different cluster numbers.
                R2 gives the explanatory power of a regression of the outcome on a quadratic in longitude and latitude."
              )
)
if(adjust=="BCH"){
syn_tab= syn_tab |>
  tinytable::group_tt(i = list("HC" = 1, "BCH" = 2 ))
}else{
  syn_tab= syn_tab |>
    tinytable::group_tt(i = list("HC" = 1, "IM" = 2 ))
 }

syn_tab= syn_tab |>
  tinytable::style_tt(
    i = c(1, 3),
    align = "l",
    bold=T)|>
  tinytable::style_tt(i = 0, bold=T )

return(syn_tab)
}
